# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run test:cov
    - run: npm install -g codecov
    - run: codecov -t 30ab91ef-9d66-44d1-8efa-a188abeae755
  
  e2e:

    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:4.2.6
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci 
    - run: npm run test:e2e